# Site settings
title: Ryan Kersh Design
email: rkersh2@gmail.com
description: A modern portfolio website created and managed by Ryan Kersh.
baseurl: ""
url: "http://ryankersh.com" # the base hostname & protocol for your site
github_username:  rkersh2

# Build settings
markdown: kramdown
